/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as publicRegisterRouteImport } from './routes/(public)/register'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as PortalAppRouteRouteImport } from './routes/portal/_app/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedRegistrationsRouteRouteImport } from './routes/_authenticated/registrations/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as PortalAppIndexRouteImport } from './routes/portal/_app/index'
import { Route as AuthenticatedVoucherIndexRouteImport } from './routes/_authenticated/voucher/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTrafficIndexRouteImport } from './routes/_authenticated/traffic/index'
import { Route as AuthenticatedSystemIndexRouteImport } from './routes/_authenticated/system/index'
import { Route as AuthenticatedSubscriptionsIndexRouteImport } from './routes/_authenticated/subscriptions/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedRegistrationsIndexRouteImport } from './routes/_authenticated/registrations/index'
import { Route as AuthenticatedNetworkIndexRouteImport } from './routes/_authenticated/network/index'
import { Route as AuthenticatedLogIndexRouteImport } from './routes/_authenticated/log/index'
import { Route as AuthenticatedHotspotIndexRouteImport } from './routes/_authenticated/hotspot/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as PortalAppTicketsRouteImport } from './routes/portal/_app/tickets'
import { Route as PortalAppSubscriptionsRouteImport } from './routes/portal/_app/subscriptions'
import { Route as PortalAppProfileRouteImport } from './routes/portal/_app/profile'
import { Route as PortalAppPaymentsRouteImport } from './routes/portal/_app/payments'
import { Route as AuthenticatedVoucherSalesRouteImport } from './routes/_authenticated/voucher/sales'
import { Route as AuthenticatedVoucherPrintRouteImport } from './routes/_authenticated/voucher/print'
import { Route as AuthenticatedVoucherGenerateRouteImport } from './routes/_authenticated/voucher/generate'
import { Route as AuthenticatedSettingsPaymentGatewayRouteImport } from './routes/_authenticated/settings/payment-gateway'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedReportMonthlyRouteImport } from './routes/_authenticated/report/monthly'
import { Route as AuthenticatedReportDailyRouteImport } from './routes/_authenticated/report/daily'
import { Route as AuthenticatedPppSecretsRouteImport } from './routes/_authenticated/ppp/secrets'
import { Route as AuthenticatedPppProfilesRouteImport } from './routes/_authenticated/ppp/profiles'
import { Route as AuthenticatedPppBillingRouteImport } from './routes/_authenticated/ppp/billing'
import { Route as AuthenticatedPppActiveRouteImport } from './routes/_authenticated/ppp/active'
import { Route as AuthenticatedHotspotUsersRouteImport } from './routes/_authenticated/hotspot/users'
import { Route as AuthenticatedHotspotProfilesRouteImport } from './routes/_authenticated/hotspot/profiles'
import { Route as AuthenticatedHotspotHostsRouteImport } from './routes/_authenticated/hotspot/hosts'
import { Route as AuthenticatedHotspotBillingRouteImport } from './routes/_authenticated/hotspot/billing'
import { Route as AuthenticatedHotspotActiveRouteImport } from './routes/_authenticated/hotspot/active'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as PortalAppInvoicesIndexRouteImport } from './routes/portal/_app/invoices/index'
import { Route as AuthenticatedAdminWhatsappIndexRouteImport } from './routes/_authenticated/admin/whatsapp/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin/settings/index'
import { Route as AuthenticatedAdminRoutersIndexRouteImport } from './routes/_authenticated/admin/routers/index'
import { Route as AuthenticatedAdminNotificationsIndexRouteImport } from './routes/_authenticated/admin/notifications/index'
import { Route as AuthenticatedAdminMessageTemplatesIndexRouteImport } from './routes/_authenticated/admin/message-templates/index'
import { Route as AuthenticatedAdminAuditLogsIndexRouteImport } from './routes/_authenticated/admin/audit-logs/index'
import { Route as PortalAppInvoicesIdRouteImport } from './routes/portal/_app/invoices/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/(public)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAppRouteRoute = PortalAppRouteRouteImport.update({
  id: '/portal/_app',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegistrationsRouteRoute =
  AuthenticatedRegistrationsRouteRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalAppIndexRoute = PortalAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalAppRouteRoute,
} as any)
const AuthenticatedVoucherIndexRoute =
  AuthenticatedVoucherIndexRouteImport.update({
    id: '/voucher/',
    path: '/voucher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrafficIndexRoute =
  AuthenticatedTrafficIndexRouteImport.update({
    id: '/traffic/',
    path: '/traffic/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemIndexRoute =
  AuthenticatedSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionsIndexRoute =
  AuthenticatedSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegistrationsIndexRoute =
  AuthenticatedRegistrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRegistrationsRouteRoute,
  } as any)
const AuthenticatedNetworkIndexRoute =
  AuthenticatedNetworkIndexRouteImport.update({
    id: '/network/',
    path: '/network/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogIndexRoute = AuthenticatedLogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHotspotIndexRoute =
  AuthenticatedHotspotIndexRouteImport.update({
    id: '/hotspot/',
    path: '/hotspot/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PortalAppTicketsRoute = PortalAppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => PortalAppRouteRoute,
} as any)
const PortalAppSubscriptionsRoute = PortalAppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => PortalAppRouteRoute,
} as any)
const PortalAppProfileRoute = PortalAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalAppRouteRoute,
} as any)
const PortalAppPaymentsRoute = PortalAppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalAppRouteRoute,
} as any)
const AuthenticatedVoucherSalesRoute =
  AuthenticatedVoucherSalesRouteImport.update({
    id: '/voucher/sales',
    path: '/voucher/sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVoucherPrintRoute =
  AuthenticatedVoucherPrintRouteImport.update({
    id: '/voucher/print',
    path: '/voucher/print',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVoucherGenerateRoute =
  AuthenticatedVoucherGenerateRouteImport.update({
    id: '/voucher/generate',
    path: '/voucher/generate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPaymentGatewayRoute =
  AuthenticatedSettingsPaymentGatewayRouteImport.update({
    id: '/payment-gateway',
    path: '/payment-gateway',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReportMonthlyRoute =
  AuthenticatedReportMonthlyRouteImport.update({
    id: '/report/monthly',
    path: '/report/monthly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportDailyRoute =
  AuthenticatedReportDailyRouteImport.update({
    id: '/report/daily',
    path: '/report/daily',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPppSecretsRoute = AuthenticatedPppSecretsRouteImport.update({
  id: '/ppp/secrets',
  path: '/ppp/secrets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPppProfilesRoute =
  AuthenticatedPppProfilesRouteImport.update({
    id: '/ppp/profiles',
    path: '/ppp/profiles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPppBillingRoute = AuthenticatedPppBillingRouteImport.update({
  id: '/ppp/billing',
  path: '/ppp/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPppActiveRoute = AuthenticatedPppActiveRouteImport.update({
  id: '/ppp/active',
  path: '/ppp/active',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHotspotUsersRoute =
  AuthenticatedHotspotUsersRouteImport.update({
    id: '/hotspot/users',
    path: '/hotspot/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotspotProfilesRoute =
  AuthenticatedHotspotProfilesRouteImport.update({
    id: '/hotspot/profiles',
    path: '/hotspot/profiles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotspotHostsRoute =
  AuthenticatedHotspotHostsRouteImport.update({
    id: '/hotspot/hosts',
    path: '/hotspot/hosts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotspotBillingRoute =
  AuthenticatedHotspotBillingRouteImport.update({
    id: '/hotspot/billing',
    path: '/hotspot/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotspotActiveRoute =
  AuthenticatedHotspotActiveRouteImport.update({
    id: '/hotspot/active',
    path: '/hotspot/active',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PortalAppInvoicesIndexRoute = PortalAppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => PortalAppRouteRoute,
} as any)
const AuthenticatedAdminWhatsappIndexRoute =
  AuthenticatedAdminWhatsappIndexRouteImport.update({
    id: '/whatsapp/',
    path: '/whatsapp/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRoutersIndexRoute =
  AuthenticatedAdminRoutersIndexRouteImport.update({
    id: '/routers/',
    path: '/routers/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsIndexRoute =
  AuthenticatedAdminNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessageTemplatesIndexRoute =
  AuthenticatedAdminMessageTemplatesIndexRouteImport.update({
    id: '/message-templates/',
    path: '/message-templates/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogsIndexRoute =
  AuthenticatedAdminAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const PortalAppInvoicesIdRoute = PortalAppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => PortalAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/registrations': typeof AuthenticatedRegistrationsRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/portal': typeof PortalAppRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/register': typeof publicRegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/hotspot/active': typeof AuthenticatedHotspotActiveRoute
  '/hotspot/billing': typeof AuthenticatedHotspotBillingRoute
  '/hotspot/hosts': typeof AuthenticatedHotspotHostsRoute
  '/hotspot/profiles': typeof AuthenticatedHotspotProfilesRoute
  '/hotspot/users': typeof AuthenticatedHotspotUsersRoute
  '/ppp/active': typeof AuthenticatedPppActiveRoute
  '/ppp/billing': typeof AuthenticatedPppBillingRoute
  '/ppp/profiles': typeof AuthenticatedPppProfilesRoute
  '/ppp/secrets': typeof AuthenticatedPppSecretsRoute
  '/report/daily': typeof AuthenticatedReportDailyRoute
  '/report/monthly': typeof AuthenticatedReportMonthlyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/payment-gateway': typeof AuthenticatedSettingsPaymentGatewayRoute
  '/voucher/generate': typeof AuthenticatedVoucherGenerateRoute
  '/voucher/print': typeof AuthenticatedVoucherPrintRoute
  '/voucher/sales': typeof AuthenticatedVoucherSalesRoute
  '/portal/payments': typeof PortalAppPaymentsRoute
  '/portal/profile': typeof PortalAppProfileRoute
  '/portal/subscriptions': typeof PortalAppSubscriptionsRoute
  '/portal/tickets': typeof PortalAppTicketsRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/hotspot/': typeof AuthenticatedHotspotIndexRoute
  '/log/': typeof AuthenticatedLogIndexRoute
  '/network/': typeof AuthenticatedNetworkIndexRoute
  '/registrations/': typeof AuthenticatedRegistrationsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/subscriptions/': typeof AuthenticatedSubscriptionsIndexRoute
  '/system/': typeof AuthenticatedSystemIndexRoute
  '/traffic/': typeof AuthenticatedTrafficIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/voucher/': typeof AuthenticatedVoucherIndexRoute
  '/portal/': typeof PortalAppIndexRoute
  '/portal/invoices/$id': typeof PortalAppInvoicesIdRoute
  '/admin/audit-logs/': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/admin/message-templates/': typeof AuthenticatedAdminMessageTemplatesIndexRoute
  '/admin/notifications/': typeof AuthenticatedAdminNotificationsIndexRoute
  '/admin/routers/': typeof AuthenticatedAdminRoutersIndexRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/whatsapp/': typeof AuthenticatedAdminWhatsappIndexRoute
  '/portal/invoices/': typeof PortalAppInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/register': typeof publicRegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/hotspot/active': typeof AuthenticatedHotspotActiveRoute
  '/hotspot/billing': typeof AuthenticatedHotspotBillingRoute
  '/hotspot/hosts': typeof AuthenticatedHotspotHostsRoute
  '/hotspot/profiles': typeof AuthenticatedHotspotProfilesRoute
  '/hotspot/users': typeof AuthenticatedHotspotUsersRoute
  '/ppp/active': typeof AuthenticatedPppActiveRoute
  '/ppp/billing': typeof AuthenticatedPppBillingRoute
  '/ppp/profiles': typeof AuthenticatedPppProfilesRoute
  '/ppp/secrets': typeof AuthenticatedPppSecretsRoute
  '/report/daily': typeof AuthenticatedReportDailyRoute
  '/report/monthly': typeof AuthenticatedReportMonthlyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/payment-gateway': typeof AuthenticatedSettingsPaymentGatewayRoute
  '/voucher/generate': typeof AuthenticatedVoucherGenerateRoute
  '/voucher/print': typeof AuthenticatedVoucherPrintRoute
  '/voucher/sales': typeof AuthenticatedVoucherSalesRoute
  '/portal/payments': typeof PortalAppPaymentsRoute
  '/portal/profile': typeof PortalAppProfileRoute
  '/portal/subscriptions': typeof PortalAppSubscriptionsRoute
  '/portal/tickets': typeof PortalAppTicketsRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/hotspot': typeof AuthenticatedHotspotIndexRoute
  '/log': typeof AuthenticatedLogIndexRoute
  '/network': typeof AuthenticatedNetworkIndexRoute
  '/registrations': typeof AuthenticatedRegistrationsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/traffic': typeof AuthenticatedTrafficIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/voucher': typeof AuthenticatedVoucherIndexRoute
  '/portal': typeof PortalAppIndexRoute
  '/portal/invoices/$id': typeof PortalAppInvoicesIdRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/admin/message-templates': typeof AuthenticatedAdminMessageTemplatesIndexRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsIndexRoute
  '/admin/routers': typeof AuthenticatedAdminRoutersIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappIndexRoute
  '/portal/invoices': typeof PortalAppInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/registrations': typeof AuthenticatedRegistrationsRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/portal/_app': typeof PortalAppRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(public)/register': typeof publicRegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/hotspot/active': typeof AuthenticatedHotspotActiveRoute
  '/_authenticated/hotspot/billing': typeof AuthenticatedHotspotBillingRoute
  '/_authenticated/hotspot/hosts': typeof AuthenticatedHotspotHostsRoute
  '/_authenticated/hotspot/profiles': typeof AuthenticatedHotspotProfilesRoute
  '/_authenticated/hotspot/users': typeof AuthenticatedHotspotUsersRoute
  '/_authenticated/ppp/active': typeof AuthenticatedPppActiveRoute
  '/_authenticated/ppp/billing': typeof AuthenticatedPppBillingRoute
  '/_authenticated/ppp/profiles': typeof AuthenticatedPppProfilesRoute
  '/_authenticated/ppp/secrets': typeof AuthenticatedPppSecretsRoute
  '/_authenticated/report/daily': typeof AuthenticatedReportDailyRoute
  '/_authenticated/report/monthly': typeof AuthenticatedReportMonthlyRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/payment-gateway': typeof AuthenticatedSettingsPaymentGatewayRoute
  '/_authenticated/voucher/generate': typeof AuthenticatedVoucherGenerateRoute
  '/_authenticated/voucher/print': typeof AuthenticatedVoucherPrintRoute
  '/_authenticated/voucher/sales': typeof AuthenticatedVoucherSalesRoute
  '/portal/_app/payments': typeof PortalAppPaymentsRoute
  '/portal/_app/profile': typeof PortalAppProfileRoute
  '/portal/_app/subscriptions': typeof PortalAppSubscriptionsRoute
  '/portal/_app/tickets': typeof PortalAppTicketsRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/hotspot/': typeof AuthenticatedHotspotIndexRoute
  '/_authenticated/log/': typeof AuthenticatedLogIndexRoute
  '/_authenticated/network/': typeof AuthenticatedNetworkIndexRoute
  '/_authenticated/registrations/': typeof AuthenticatedRegistrationsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/subscriptions/': typeof AuthenticatedSubscriptionsIndexRoute
  '/_authenticated/system/': typeof AuthenticatedSystemIndexRoute
  '/_authenticated/traffic/': typeof AuthenticatedTrafficIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/voucher/': typeof AuthenticatedVoucherIndexRoute
  '/portal/_app/': typeof PortalAppIndexRoute
  '/portal/_app/invoices/$id': typeof PortalAppInvoicesIdRoute
  '/_authenticated/admin/audit-logs/': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/_authenticated/admin/message-templates/': typeof AuthenticatedAdminMessageTemplatesIndexRoute
  '/_authenticated/admin/notifications/': typeof AuthenticatedAdminNotificationsIndexRoute
  '/_authenticated/admin/routers/': typeof AuthenticatedAdminRoutersIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/admin/whatsapp/': typeof AuthenticatedAdminWhatsappIndexRoute
  '/portal/_app/invoices/': typeof PortalAppInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/registrations'
    | '/settings'
    | '/portal'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/register'
    | '/dashboard'
    | '/portal/login'
    | '/errors/$error'
    | '/hotspot/active'
    | '/hotspot/billing'
    | '/hotspot/hosts'
    | '/hotspot/profiles'
    | '/hotspot/users'
    | '/ppp/active'
    | '/ppp/billing'
    | '/ppp/profiles'
    | '/ppp/secrets'
    | '/report/daily'
    | '/report/monthly'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/payment-gateway'
    | '/voucher/generate'
    | '/voucher/print'
    | '/voucher/sales'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/subscriptions'
    | '/portal/tickets'
    | '/customers/'
    | '/help-center/'
    | '/hotspot/'
    | '/log/'
    | '/network/'
    | '/registrations/'
    | '/reports/'
    | '/settings/'
    | '/subscriptions/'
    | '/system/'
    | '/traffic/'
    | '/users/'
    | '/voucher/'
    | '/portal/'
    | '/portal/invoices/$id'
    | '/admin/audit-logs/'
    | '/admin/message-templates/'
    | '/admin/notifications/'
    | '/admin/routers/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/admin/whatsapp/'
    | '/portal/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/register'
    | '/dashboard'
    | '/portal/login'
    | '/errors/$error'
    | '/hotspot/active'
    | '/hotspot/billing'
    | '/hotspot/hosts'
    | '/hotspot/profiles'
    | '/hotspot/users'
    | '/ppp/active'
    | '/ppp/billing'
    | '/ppp/profiles'
    | '/ppp/secrets'
    | '/report/daily'
    | '/report/monthly'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/payment-gateway'
    | '/voucher/generate'
    | '/voucher/print'
    | '/voucher/sales'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/subscriptions'
    | '/portal/tickets'
    | '/customers'
    | '/help-center'
    | '/hotspot'
    | '/log'
    | '/network'
    | '/registrations'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/system'
    | '/traffic'
    | '/users'
    | '/voucher'
    | '/portal'
    | '/portal/invoices/$id'
    | '/admin/audit-logs'
    | '/admin/message-templates'
    | '/admin/notifications'
    | '/admin/routers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/portal/invoices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/registrations'
    | '/_authenticated/settings'
    | '/portal/_app'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(public)/register'
    | '/_authenticated/dashboard'
    | '/portal/login'
    | '/_authenticated/errors/$error'
    | '/_authenticated/hotspot/active'
    | '/_authenticated/hotspot/billing'
    | '/_authenticated/hotspot/hosts'
    | '/_authenticated/hotspot/profiles'
    | '/_authenticated/hotspot/users'
    | '/_authenticated/ppp/active'
    | '/_authenticated/ppp/billing'
    | '/_authenticated/ppp/profiles'
    | '/_authenticated/ppp/secrets'
    | '/_authenticated/report/daily'
    | '/_authenticated/report/monthly'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/payment-gateway'
    | '/_authenticated/voucher/generate'
    | '/_authenticated/voucher/print'
    | '/_authenticated/voucher/sales'
    | '/portal/_app/payments'
    | '/portal/_app/profile'
    | '/portal/_app/subscriptions'
    | '/portal/_app/tickets'
    | '/_authenticated/customers/'
    | '/_authenticated/help-center/'
    | '/_authenticated/hotspot/'
    | '/_authenticated/log/'
    | '/_authenticated/network/'
    | '/_authenticated/registrations/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/_authenticated/subscriptions/'
    | '/_authenticated/system/'
    | '/_authenticated/traffic/'
    | '/_authenticated/users/'
    | '/_authenticated/voucher/'
    | '/portal/_app/'
    | '/portal/_app/invoices/$id'
    | '/_authenticated/admin/audit-logs/'
    | '/_authenticated/admin/message-templates/'
    | '/_authenticated/admin/notifications/'
    | '/_authenticated/admin/routers/'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/admin/whatsapp/'
    | '/portal/_app/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PortalAppRouteRoute: typeof PortalAppRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  publicRegisterRoute: typeof publicRegisterRoute
  PortalLoginRoute: typeof PortalLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/_app': {
      id: '/portal/_app'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registrations': {
      id: '/_authenticated/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof AuthenticatedRegistrationsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/_app/': {
      id: '/portal/_app/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalAppIndexRouteImport
      parentRoute: typeof PortalAppRouteRoute
    }
    '/_authenticated/voucher/': {
      id: '/_authenticated/voucher/'
      path: '/voucher'
      fullPath: '/voucher/'
      preLoaderRoute: typeof AuthenticatedVoucherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/traffic/': {
      id: '/_authenticated/traffic/'
      path: '/traffic'
      fullPath: '/traffic/'
      preLoaderRoute: typeof AuthenticatedTrafficIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/': {
      id: '/_authenticated/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof AuthenticatedSystemIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions/': {
      id: '/_authenticated/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof AuthenticatedSubscriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registrations/': {
      id: '/_authenticated/registrations/'
      path: '/'
      fullPath: '/registrations/'
      preLoaderRoute: typeof AuthenticatedRegistrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRegistrationsRouteRoute
    }
    '/_authenticated/network/': {
      id: '/_authenticated/network/'
      path: '/network'
      fullPath: '/network/'
      preLoaderRoute: typeof AuthenticatedNetworkIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/': {
      id: '/_authenticated/log/'
      path: '/log'
      fullPath: '/log/'
      preLoaderRoute: typeof AuthenticatedLogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotspot/': {
      id: '/_authenticated/hotspot/'
      path: '/hotspot'
      fullPath: '/hotspot/'
      preLoaderRoute: typeof AuthenticatedHotspotIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/_app/tickets': {
      id: '/portal/_app/tickets'
      path: '/tickets'
      fullPath: '/portal/tickets'
      preLoaderRoute: typeof PortalAppTicketsRouteImport
      parentRoute: typeof PortalAppRouteRoute
    }
    '/portal/_app/subscriptions': {
      id: '/portal/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/portal/subscriptions'
      preLoaderRoute: typeof PortalAppSubscriptionsRouteImport
      parentRoute: typeof PortalAppRouteRoute
    }
    '/portal/_app/profile': {
      id: '/portal/_app/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalAppProfileRouteImport
      parentRoute: typeof PortalAppRouteRoute
    }
    '/portal/_app/payments': {
      id: '/portal/_app/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalAppPaymentsRouteImport
      parentRoute: typeof PortalAppRouteRoute
    }
    '/_authenticated/voucher/sales': {
      id: '/_authenticated/voucher/sales'
      path: '/voucher/sales'
      fullPath: '/voucher/sales'
      preLoaderRoute: typeof AuthenticatedVoucherSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voucher/print': {
      id: '/_authenticated/voucher/print'
      path: '/voucher/print'
      fullPath: '/voucher/print'
      preLoaderRoute: typeof AuthenticatedVoucherPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voucher/generate': {
      id: '/_authenticated/voucher/generate'
      path: '/voucher/generate'
      fullPath: '/voucher/generate'
      preLoaderRoute: typeof AuthenticatedVoucherGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/payment-gateway': {
      id: '/_authenticated/settings/payment-gateway'
      path: '/payment-gateway'
      fullPath: '/settings/payment-gateway'
      preLoaderRoute: typeof AuthenticatedSettingsPaymentGatewayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/report/monthly': {
      id: '/_authenticated/report/monthly'
      path: '/report/monthly'
      fullPath: '/report/monthly'
      preLoaderRoute: typeof AuthenticatedReportMonthlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/daily': {
      id: '/_authenticated/report/daily'
      path: '/report/daily'
      fullPath: '/report/daily'
      preLoaderRoute: typeof AuthenticatedReportDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ppp/secrets': {
      id: '/_authenticated/ppp/secrets'
      path: '/ppp/secrets'
      fullPath: '/ppp/secrets'
      preLoaderRoute: typeof AuthenticatedPppSecretsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ppp/profiles': {
      id: '/_authenticated/ppp/profiles'
      path: '/ppp/profiles'
      fullPath: '/ppp/profiles'
      preLoaderRoute: typeof AuthenticatedPppProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ppp/billing': {
      id: '/_authenticated/ppp/billing'
      path: '/ppp/billing'
      fullPath: '/ppp/billing'
      preLoaderRoute: typeof AuthenticatedPppBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ppp/active': {
      id: '/_authenticated/ppp/active'
      path: '/ppp/active'
      fullPath: '/ppp/active'
      preLoaderRoute: typeof AuthenticatedPppActiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotspot/users': {
      id: '/_authenticated/hotspot/users'
      path: '/hotspot/users'
      fullPath: '/hotspot/users'
      preLoaderRoute: typeof AuthenticatedHotspotUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotspot/profiles': {
      id: '/_authenticated/hotspot/profiles'
      path: '/hotspot/profiles'
      fullPath: '/hotspot/profiles'
      preLoaderRoute: typeof AuthenticatedHotspotProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotspot/hosts': {
      id: '/_authenticated/hotspot/hosts'
      path: '/hotspot/hosts'
      fullPath: '/hotspot/hosts'
      preLoaderRoute: typeof AuthenticatedHotspotHostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotspot/billing': {
      id: '/_authenticated/hotspot/billing'
      path: '/hotspot/billing'
      fullPath: '/hotspot/billing'
      preLoaderRoute: typeof AuthenticatedHotspotBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotspot/active': {
      id: '/_authenticated/hotspot/active'
      path: '/hotspot/active'
      fullPath: '/hotspot/active'
      preLoaderRoute: typeof AuthenticatedHotspotActiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/_app/invoices/': {
      id: '/portal/_app/invoices/'
      path: '/invoices'
      fullPath: '/portal/invoices/'
      preLoaderRoute: typeof PortalAppInvoicesIndexRouteImport
      parentRoute: typeof PortalAppRouteRoute
    }
    '/_authenticated/admin/whatsapp/': {
      id: '/_authenticated/admin/whatsapp/'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp/'
      preLoaderRoute: typeof AuthenticatedAdminWhatsappIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/routers/': {
      id: '/_authenticated/admin/routers/'
      path: '/routers'
      fullPath: '/admin/routers/'
      preLoaderRoute: typeof AuthenticatedAdminRoutersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications/': {
      id: '/_authenticated/admin/notifications/'
      path: '/notifications'
      fullPath: '/admin/notifications/'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/message-templates/': {
      id: '/_authenticated/admin/message-templates/'
      path: '/message-templates'
      fullPath: '/admin/message-templates/'
      preLoaderRoute: typeof AuthenticatedAdminMessageTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-logs/': {
      id: '/_authenticated/admin/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/portal/_app/invoices/$id': {
      id: '/portal/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/portal/invoices/$id'
      preLoaderRoute: typeof PortalAppInvoicesIdRouteImport
      parentRoute: typeof PortalAppRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditLogsIndexRoute: typeof AuthenticatedAdminAuditLogsIndexRoute
  AuthenticatedAdminMessageTemplatesIndexRoute: typeof AuthenticatedAdminMessageTemplatesIndexRoute
  AuthenticatedAdminNotificationsIndexRoute: typeof AuthenticatedAdminNotificationsIndexRoute
  AuthenticatedAdminRoutersIndexRoute: typeof AuthenticatedAdminRoutersIndexRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedAdminWhatsappIndexRoute: typeof AuthenticatedAdminWhatsappIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditLogsIndexRoute:
      AuthenticatedAdminAuditLogsIndexRoute,
    AuthenticatedAdminMessageTemplatesIndexRoute:
      AuthenticatedAdminMessageTemplatesIndexRoute,
    AuthenticatedAdminNotificationsIndexRoute:
      AuthenticatedAdminNotificationsIndexRoute,
    AuthenticatedAdminRoutersIndexRoute: AuthenticatedAdminRoutersIndexRoute,
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
    AuthenticatedAdminWhatsappIndexRoute: AuthenticatedAdminWhatsappIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRegistrationsRouteRouteChildren {
  AuthenticatedRegistrationsIndexRoute: typeof AuthenticatedRegistrationsIndexRoute
}

const AuthenticatedRegistrationsRouteRouteChildren: AuthenticatedRegistrationsRouteRouteChildren =
  {
    AuthenticatedRegistrationsIndexRoute: AuthenticatedRegistrationsIndexRoute,
  }

const AuthenticatedRegistrationsRouteRouteWithChildren =
  AuthenticatedRegistrationsRouteRoute._addFileChildren(
    AuthenticatedRegistrationsRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPaymentGatewayRoute: typeof AuthenticatedSettingsPaymentGatewayRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsPaymentGatewayRoute:
      AuthenticatedSettingsPaymentGatewayRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedRegistrationsRouteRoute: typeof AuthenticatedRegistrationsRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHotspotActiveRoute: typeof AuthenticatedHotspotActiveRoute
  AuthenticatedHotspotBillingRoute: typeof AuthenticatedHotspotBillingRoute
  AuthenticatedHotspotHostsRoute: typeof AuthenticatedHotspotHostsRoute
  AuthenticatedHotspotProfilesRoute: typeof AuthenticatedHotspotProfilesRoute
  AuthenticatedHotspotUsersRoute: typeof AuthenticatedHotspotUsersRoute
  AuthenticatedPppActiveRoute: typeof AuthenticatedPppActiveRoute
  AuthenticatedPppBillingRoute: typeof AuthenticatedPppBillingRoute
  AuthenticatedPppProfilesRoute: typeof AuthenticatedPppProfilesRoute
  AuthenticatedPppSecretsRoute: typeof AuthenticatedPppSecretsRoute
  AuthenticatedReportDailyRoute: typeof AuthenticatedReportDailyRoute
  AuthenticatedReportMonthlyRoute: typeof AuthenticatedReportMonthlyRoute
  AuthenticatedVoucherGenerateRoute: typeof AuthenticatedVoucherGenerateRoute
  AuthenticatedVoucherPrintRoute: typeof AuthenticatedVoucherPrintRoute
  AuthenticatedVoucherSalesRoute: typeof AuthenticatedVoucherSalesRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedHotspotIndexRoute: typeof AuthenticatedHotspotIndexRoute
  AuthenticatedLogIndexRoute: typeof AuthenticatedLogIndexRoute
  AuthenticatedNetworkIndexRoute: typeof AuthenticatedNetworkIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSubscriptionsIndexRoute: typeof AuthenticatedSubscriptionsIndexRoute
  AuthenticatedSystemIndexRoute: typeof AuthenticatedSystemIndexRoute
  AuthenticatedTrafficIndexRoute: typeof AuthenticatedTrafficIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVoucherIndexRoute: typeof AuthenticatedVoucherIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedRegistrationsRouteRoute:
    AuthenticatedRegistrationsRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHotspotActiveRoute: AuthenticatedHotspotActiveRoute,
  AuthenticatedHotspotBillingRoute: AuthenticatedHotspotBillingRoute,
  AuthenticatedHotspotHostsRoute: AuthenticatedHotspotHostsRoute,
  AuthenticatedHotspotProfilesRoute: AuthenticatedHotspotProfilesRoute,
  AuthenticatedHotspotUsersRoute: AuthenticatedHotspotUsersRoute,
  AuthenticatedPppActiveRoute: AuthenticatedPppActiveRoute,
  AuthenticatedPppBillingRoute: AuthenticatedPppBillingRoute,
  AuthenticatedPppProfilesRoute: AuthenticatedPppProfilesRoute,
  AuthenticatedPppSecretsRoute: AuthenticatedPppSecretsRoute,
  AuthenticatedReportDailyRoute: AuthenticatedReportDailyRoute,
  AuthenticatedReportMonthlyRoute: AuthenticatedReportMonthlyRoute,
  AuthenticatedVoucherGenerateRoute: AuthenticatedVoucherGenerateRoute,
  AuthenticatedVoucherPrintRoute: AuthenticatedVoucherPrintRoute,
  AuthenticatedVoucherSalesRoute: AuthenticatedVoucherSalesRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedHotspotIndexRoute: AuthenticatedHotspotIndexRoute,
  AuthenticatedLogIndexRoute: AuthenticatedLogIndexRoute,
  AuthenticatedNetworkIndexRoute: AuthenticatedNetworkIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSubscriptionsIndexRoute: AuthenticatedSubscriptionsIndexRoute,
  AuthenticatedSystemIndexRoute: AuthenticatedSystemIndexRoute,
  AuthenticatedTrafficIndexRoute: AuthenticatedTrafficIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVoucherIndexRoute: AuthenticatedVoucherIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalAppRouteRouteChildren {
  PortalAppPaymentsRoute: typeof PortalAppPaymentsRoute
  PortalAppProfileRoute: typeof PortalAppProfileRoute
  PortalAppSubscriptionsRoute: typeof PortalAppSubscriptionsRoute
  PortalAppTicketsRoute: typeof PortalAppTicketsRoute
  PortalAppIndexRoute: typeof PortalAppIndexRoute
  PortalAppInvoicesIdRoute: typeof PortalAppInvoicesIdRoute
  PortalAppInvoicesIndexRoute: typeof PortalAppInvoicesIndexRoute
}

const PortalAppRouteRouteChildren: PortalAppRouteRouteChildren = {
  PortalAppPaymentsRoute: PortalAppPaymentsRoute,
  PortalAppProfileRoute: PortalAppProfileRoute,
  PortalAppSubscriptionsRoute: PortalAppSubscriptionsRoute,
  PortalAppTicketsRoute: PortalAppTicketsRoute,
  PortalAppIndexRoute: PortalAppIndexRoute,
  PortalAppInvoicesIdRoute: PortalAppInvoicesIdRoute,
  PortalAppInvoicesIndexRoute: PortalAppInvoicesIndexRoute,
}

const PortalAppRouteRouteWithChildren = PortalAppRouteRoute._addFileChildren(
  PortalAppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PortalAppRouteRoute: PortalAppRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  publicRegisterRoute: publicRegisterRoute,
  PortalLoginRoute: PortalLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
